version: '3'
services:
  email:
    build: ./
    ports:
      - "3000:3000"
    environment:
      DB_NAME: monitor_email
      DB_HOST: email_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      TOKEN: 40797d32-4825-4391-a2c3-051ab9e79a77
    networks:
      - email_net
    depends_on:
      email_db:
        condition: service_healthy
  email_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monitor_email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - email_net
networks:
  email_net:
    driver: bridge
  